### ISSUE TITLE
Add support for stop_motion service

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#10]
As mandated by the [_Industrial Robot Driver Specification_](http://www.ros.org/wiki/Industrial/Industrial_Robot_Driver_Spec), section 1.3.3, under _Services_:

> - stop_motion ([industrial_msgs/StopMotion](http://ros.org/doc/groovy/api/industrial_msgs/html/srv/StopMotion.html))
>   -  stop current robot motion
>   -  can resume motion by sending a new motion command

**Comment by JeremyZoss** [comment]
This should already be supported by the core industrial_robot_client libraries.  See [here](https://github.com/ros-industrial/industrial_core/blob/groovy-devel/industrial_robot_client/src/joint_trajectory_interface.cpp#L104) and [here](https://github.com/ros-industrial/industrial_core/blob/groovy-devel/industrial_robot_client/src/joint_trajectory_interface.cpp#L327).

Currently, it always returns TRUE.  This could be enhanced, but we would want to clarify whether true/false status reflects whether the robot _received_ the message (e.g. ACK) or whether the motion was actually stopped (SUCCESS).  The latter would likely require custom support on each manufacturer's driver.

**Comment by gavanderhoorn** [comment]
As in #11: as `fanuc_driver` subclasses the `industrial_robot_client` it automatically supports this.

As to the comment on the current implementation, see ros-industrial/industrial_core#26.
