### ISSUE TITLE
Clarify compatibility with ROS indigo / plan Indigo release

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/fanuc#124]
There is no information provided about the support of `fanuc` packages with ROS Indigo.

**Comment by gavanderhoorn** [comment]
No release has been announced on the wiki or mailinglist, no.

A ticket documenting the planning for ROS-Industrial as a whole can be found at ros-industrial/ros_industrial_issues#30. The `indigo` milestone for the `fanuc` package related to that can be found at [fanuc/milestones/indigo](https://github.com/ros-industrial/fanuc/milestones/indigo).

**Comment by gavanderhoorn** [comment]
As far as I've tested, all packages currently in `hydro-devel` (of both this repository, and the `fanuc_experimental` package) should work in `indigo`. In the absence of a binary release, building from source should allow you to use them anyway -- at least for now.

Is there anything in particular you need, or is this just a general request for an Indigo release?

**Comment by gavanderhoorn** [comment]
The _support_ prefix is used to indicate that the ticket is related to `fanuc_X_support` packages.

**Comment by VictorLamoine** [comment]
That is precisely what I was wondering; thanks for the feedback.
I hope to get back and help with the developments in a few days when I'll be acquainted with ROS / ROS-Industrial. (sorry for the bad naming I'll take a look at the conventions).

**Comment by gavanderhoorn** [comment]
No problem: it's only something I've defined myself, for this repository. Nothing official.

Thanks for reporting: things like this help to get/keep things high on my TODO list.

**Comment by gavanderhoorn** [comment]
O and for such generic questions, you might want to send a message to the ROS-Industrial [mailing list](https://groups.google.com/forum/?fromgroups#!forum/swri-ros-pkg-dev) in the future. It's well read and you should get an answer there quickly as well.

**Comment by gavanderhoorn** [comment]
See also #126.

**Comment by gavanderhoorn** [comment]
Closing as #126 should take care of this.
