### ISSUE TITLE
wiki: confirm changing $SCR.$MAXNUMTASKS is no longer needed

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#128]
The Hydro configuration tutorial does not have a section on the system variable `$SCR.$MAXNUMTASKS` anymore (the Groovy one did). The default value is 4, which should be sufficient to run the ROS-Industrial Karel & TP programs.

This should be verified (again), and the section should perhaps be removed from the Groovy tutorial as well.

**Comment by VictorLamoine** [comment]
On the M10iA I use the value was 1. Note it is a lent robot and no "hard" reset has been done.

**Comment by gavanderhoorn** [comment]
Ok. That is good to know. Thanks for that.

I've been working on a tool that checks system settings and loaded options to make sure they are compatible with ROS-Industrial requirements. `$SCR.$MAXNUMTASKS` is already on the list of things to check.

**Comment by gavanderhoorn** [comment]
I've uncommented the section on `$MAXNUMTASKS` in the Hydro configuration tutorial. Even if a default value works, users might have a controller where the variable was changed from its default (at some point in the controller's history), and they would need to check and update it.

Thanks @VictorLamoine for reporting this.
