### ISSUE TITLE
wiki: add section on controller Karel configuration to installation tutorial

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/fanuc#129]
Make sure Karel is enabled on the controller by checking the `KAREL_ENB` (= 1) system variable.

**Comment by gavanderhoorn** [comment]
Thanks for reporting this.

I'm all in favour of making the tutorials as informative as possible, but they do assume _some_ level of experience with Fanuc controllers and robots:

> Note: This tutorial assumes familiarity with Fanuc controller cabinets, the Teach Pendant and the Roboguide environment. For more information on any of the steps in this tutorial, consult the documentation on these subjects provided by Fanuc Robotics.

I'll see about integrating this in a way that it doesn't overload readers with information.

**Comment by VictorLamoine** [comment]
I have sent a "pull request" in the [Troubleshooting](http://wiki.ros.org/fanuc_driver/Troubleshooting#Configuration) section of the wiki

**Comment by gavanderhoorn** [comment]
Thanks for that.

I might move this to another page though, as the _Troubleshooting_ page is more for problems users might encounter while using the software.

**Comment by gavanderhoorn** [comment]
I've changed the text a bit, to better reflect what is going on (Karel is 'enabled', it's just the UI that is not, afaik).

**Comment by VictorLamoine** [comment]
:+1:

**Comment by gavanderhoorn** [comment]
Marking as fixed for now. Perhaps this is a good place for this kind of information.
