### ISSUE TITLE
Release into Jade

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/fanuc#180]
MoveIt! is now using the fanuc m10ia for its example benchmark in its [benchmark suite](https://github.com/ros-planning/moveit_ros/pull/616), but the benchmark suite only runs on Jade. It would be great if this was available in jade as well. Thanks!

**Comment by gavanderhoorn** [comment]
I'd be willing to do this, but I can't before `industrial_core` is released into Jade.

Afaik a Jade release of those packages is planned for January next year.

**Comment by gavanderhoorn** [comment]
I'll mark this as blocked for now, and will come back to it once `industrial_core` is released.

**Comment by shaun-edwards** [comment]
January is the date, but I can see about moving this date up since there is a good reason.

**Comment by davetcoleman** [comment]
Not a huge deal, I was just putting in my vote of support. Thanks for providing a date

**Comment by gavanderhoorn** [comment]
Yeah, I figured as much.

Thanks for putting it on my TODO list.

**Comment by gavanderhoorn** [comment]
First step: get docs built (ros/rosdistro#9960).

**Comment by gavanderhoorn** [comment]
Can be done now that `industrial_core` is in Jade.

**Comment by gavanderhoorn** [comment]
As Jade has been EOL-ed, we'll not release `fanuc` for it. Instead we'll focus on Kinetic.

**Comment by gavanderhoorn** [comment]
@davetcoleman: I also believe a Jade release became less of an issue as the required M-10iA bits were copied into the relevant MoveIt test packages.

**Comment by davetcoleman** [comment]
correct. and jade is already EOL now.
