### ISSUE TITLE
Import R-2000iC/125L support pkg from A5 project

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#236]
Part of the 'reach study' pkg, but removed in a later commit.

See [fanuc_r2000ic_125l_support](https://github.com/ros-industrial-consortium/A5/tree/1c515dc21845c4f744388d706a6718fa6c308d07/a5_reach_study/robot_models/fanuc_r2000ic_125l_support).

Should go into `fanuc_experimental`.

**Comment by gavanderhoorn** [comment]
@marip8: is that pkg ok as-is, or would it need additional work before adding it to `fanuc_experimental`?

**Comment by marip8** [comment]
I believe the only thing the package is missing is the actual models for the robot (which I was unable to find at the time I created the package) and probably a few clean-up/documentation details. If you could point me to where I could get the CAD models for the R2000, I would be happy to make a pull request with the URDF

**Comment by gavanderhoorn** [comment]
So from which robot are the meshes in the `meshes` directory then?

[fanuc_r2000ic_125l_support/meshes/r2000ic_125l/visual/link_3.stl](https://github.com/ros-industrial-consortium/A5/blob/1c515dc21845c4f744388d706a6718fa6c308d07/a5_reach_study/robot_models/fanuc_r2000ic_125l_support/meshes/r2000ic_125l/visual/link_3.stl) (fi) seems like a proper mesh to me?

**Comment by marip8** [comment]
Those are actually the links from the Motoman MH180-120, which was pretty close to the same size and layout. I haven't been able to find anything more than datasheets for the R2000

**Comment by gavanderhoorn** [comment]
Ah, ok. You haven't asked Fanuc? That would be where you'd get the meshes from typically.

**Comment by gavanderhoorn** [comment]
I only have meshes for the R-2000iB/125L. Not sure whether there are any differences with the `iC`.

**Comment by gavanderhoorn** [comment]
If/when we get a request for R-2000iC/125L we can revisit this.

I have an R-2000iC/165F at the moment, not the variant discussed in the OP.

Closing.

**Comment by simonschmeisser** [comment]
@gavanderhoorn I have a project with a R-2000iC/165F upcoming, would you mind opening a PR? Thanks a lot!
