### ISSUE TITLE
[melodic]Meshes are displayed black

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/fanuc#246]
![screenshot_20181010_142041](https://user-images.githubusercontent.com/5566160/46735839-b98db500-cc97-11e8-8402-98db54fdd726.png)

My custom DAE meshes are still displayed correctly but the defaults meshes appear black with no lighting.
ros-melodic-rviz 1.13.1-0bionic.20180907.011020

**Comment by gavanderhoorn** [comment]
Seeing as the last release of RViz was back in May ([1.13.1](https://github.com/ros-visualization/rviz/releases/tag/1.13.1)) and I haven't changed anything recently, I'm inclined to first assume a local configuration issue.

Did you update any drivers? Restarted your machine?

**Comment by VictorLamoine** [comment]
This behavior is consistent across several laptops and after rebooting.
I don't know where it comes from!

**Comment by gavanderhoorn** [comment]
Are they all running the same Ubuntu version? All received the same updates?

Are other models/stls also rendered black?

**Comment by VictorLamoine** [comment]
- Kubuntu 18.04 for everyone
- Each configuration has `ros-melodic-dekstop-full` up-to-date
- nvidia 340
- nvidia 390
- intel chipset (not sure what driver is used in this case)
- DAE meshes appear fine
- STL meshes loaded as markers appear fine

**Comment by VictorLamoine** [comment]
Same problem with ABB robots from ros-industrial/abb.
@gavanderhoorn are you using Melodic?

I'm going to build a simple robot with a STL mesh and test, if it displays black I'll report to RViz

**Comment by VictorLamoine** [comment]
The issue is not related to Fanuc (see referenced issue), Gijs you can close if you want :)

The issue most probably comes from an Ogre update.

**Comment by gavanderhoorn** [comment]
> The issue is not related to Fanuc (see referenced issue), Gijs you can close if you want :)
> 
> The issue most probably comes from an Ogre update.

I was going to suggest something like this as well.

I just tested with a `melodic-desktop` container and everything looked normal.

**Comment by gavanderhoorn** [comment]
Let's see if we get more reports like this.
