### ISSUE TITLE
stop() function of moveit is performing randomly

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial/fanuc#285]
Hi, 

I am developing a desktop GUI to control my robot, there is essential functionalities and one of these is `stop` button. While testing this GUI with robot, I found out that the `stop()` function performs very randomly, sometimes it stops robot, sometimes it does not and sometimes it stops it with delay. I don't know if this is related with moveit or here, has anyone encountered this ? 
Stop functionality is very crucial for my application , any help is appreciated 
Thank you

**Comment by gavanderhoorn** [comment]
You don't tell us which driver you are using, but:

 - if you're using `fanuc_driver`: #93
 - if you're using `fanuc_driver_exp`: gavanderhoorn/fanuc_driver_exp#3

These are known issues.

See the issues for some discussion.

**Comment by gavanderhoorn** [comment]
As we already have issues for this, I'm going to close this one.

Please continue discussion on the linked issues.

**Comment by gavanderhoorn** [comment]
And @jediofgever: could you please only post issues on the `fanuc_experimental` tracker when those issues are about packages hosted by that repository? Everything else should be posted on either `fanuc` or `fanuc_driver_exp`.

**Comment by jediofgever** [comment]
Hi @gavanderhoorn,
my bad and thank you,
I use  `fanuc_driver_exp`
I am going to see the issue there
