### ISSUE TITLE
Document supported variants of a model (M-10iA)

### ISSUE THREAD

**Issue by simonschmeisser** [ros-industrial/fanuc#286]
I'm currently looking at a Fanuc M-10iA/12 and wondering if that matches the generic m10ia here. I will figure it out by comparing drawings to urdf/mesh/opw parameters but it would be nice to explicitely spell out the matching variants.

There seem to exist the following variants:

M-10iA/7L -> m10ia7l
M-10iA/8L ->  -
M-10iA/10M -> ?
M-10iA/10MS -> -
M-10iA/12 -> m10ia (seems to match)
M-10iA/12S -> -

https://www.fanuc.eu/pl/en/robots/robot-filter-page/m-10-series

I can then open a PR against the package.xml?

**Comment by gavanderhoorn** [comment]
If a variant is not mentioned, it's not supported.

Compare the manifest for the LR Mate 200iC:

https://github.com/ros-industrial/fanuc/blob/63e4bd4b484ed4a0e0f8dfd582333211b5919014/fanuc_lrmate200ic_support/package.xml#L10-L15

For the M-10iA, we have the following variants:

https://github.com/ros-industrial/fanuc/blob/63e4bd4b484ed4a0e0f8dfd582333211b5919014/fanuc_m10ia_support/package.xml#L10-L19

Afaik there is no correspondance to any other variant, unless you're thinking of the Paint and/or Welding robots.

> I can then open a PR against the readme.md?

if you find a variant isn't being mentioned, or a variant is actually supported by another one, then please do open a PR. But not to add it to the readme, but to the package manifest.

> M-10iA/12 -> m10ia ?

there used to be a "plain" M-10iA. That would be the variant supported by that model.

I don't know whether that would correspond to the `/12` variant these days.

**Comment by simonschmeisser** [comment]
> there used to be a "plain" M-10iA. That would be the variant supported by that model.

That seems to be the source of my confusion, sorry. Your model seems to be from 2009, ours is from 2014.

>I don't know whether that would correspond to the /12 variant these days.

According to https://www.fanuc.co.jp/en/product/catalog/pdf/robot/RM-10iAN(E)-02.pdf
at least the kinematics match so possibly it was just a rebranding. I'll try to find some material (mesh/picture) about wether the collision contours have changed or not.

Thanks a lot!

**Comment by gavanderhoorn** [comment]
Is this something you'd like to keep open @simonschmeisser ?

**Comment by simonschmeisser** [comment]
Hmm, I'm not sure. It was not obvious for me that there is a older "plain" model but it's not a real issue.

**Comment by gavanderhoorn** [comment]
>  I'll try to find some material (mesh/picture) about wether the collision contours have changed or not.

Did you get a chance to verify this?

**Comment by simonschmeisser** [comment]
@axelschroth I keep forgetting to ask you ... but it's in production now so I guess the answer is yes

**Comment by gavanderhoorn** [comment]
So did the collision meshes change, or did they not?

**Comment by axx-man** [comment]
I would say, that the meshes did not change. So we can use the collision meshes for the /12 variant. But I cannot tell for sure, because I did not measure the geometries and there is no high chance of collision in this particular setup anyway.
