### ISSUE TITLE
m70ic ikfast and OPW

### ISSUE THREAD

**Issue by Didier-Surface** [ros-industrial/fanuc#318]
Hi,

I am looking for the Ikfast plugin for the m70ic model, did some search around but all I could find was the support package.

And optionally the OPW parameters.

If it's not available anywhere, I will generate those myself, and share them once tested, though it would save me time if the work has been done before.

Thanks!

**Comment by gavanderhoorn** [comment]
If it's not in this repository or  `fanuc_experimental`, we don't have it.

It could be there is something available in one of the forks, but we'd have to search. Github's [network feature](https://github.com/ros-industrial/fanuc/network) is the easiest way to do that I believe.
