### ISSUE TITLE
Arm navigation pkgs depend on dry packages

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#32]
This makes it impossible to release those packages, as catkin packages cannot depend on rosbuild packages.

`planning_environment` is one such package: it is (still) dry and the arm navigation packages of the M-10 and the M-430 depend on it.

**Comment by shaun-edwards** [comment]
Aren't arm nav packages dry themselves.  The only issue I am aware of is when arm navigation depends on a catkinized ik_fast?

**Comment by gavanderhoorn** [comment]
This ticket is about the arm nav pkgs in this repository, and I've catkinised them. They work when you build them from source (and already have all the necessary dependencies installed). But they cannot be built with Bloom, due to the already mentioned dependence on rosbuild packages.

**Comment by gavanderhoorn** [comment]
This issue will not be fixed in `groovy-devel`: arm navigation packages will be removed in the `hydro-devel` branch. 

Building from source and launching them in a groovy catkin workspace will work for these arm nav pkgs. For the binary - released - version see the rosbuild versions in the old [googlecode repository](http://swri-ros-pkg.googlecode.com/svn/branches/groovy/fanuc/).
