### ISSUE TITLE
Latest version of Fanuc Driver

### ISSUE THREAD

**Issue by shota6912** [ros-industrial/fanuc#327]
We are preparing to develop CRX10iA/L with R30iB.
I tried to install fanuc_driver on my control box, but I got an error message "Karel version is too old".
I'm not sure if this is the right way to check, but my controller version is 9.4.
Can I get the appropriate driver for my control box?

**Comment by gavanderhoorn** [comment]
> We are preparing to develop CRX10iA/L

do you already have a robot support package for that robot?

> I tried to install fanuc_driver on my control box, but I got an error message "Karel version is too old".

where did you find the binaries?

> I'm not sure if this is the right way to check, but my controller version is 9.4.
> Can I get the appropriate driver for my control box?

you'll have to translate the Karel files using Roboguide or `ktrans.exe` for your specific version.

We don't have any prebuilt binaries (for that version, or any recent version really).

**Comment by gavanderhoorn** [comment]
As this is not (really) an issue with the packages in this repository, I'm going to close this.

That doesn't mean you can't comment on it any more of course. So feel free to keep doing that.

If it turns out we do need to fix something here, we can re-open.

**Comment by shota6912** [comment]
Thank you for your reply.

I choose to build Karel files using RoboGuide trial version and it worked.

We will modify the package for cr7ia to apply it to crx10ia.

We don't have R648(User Socket Messaging) function yet, so I don't know if it will work.

**Comment by gavanderhoorn** [comment]
> We will modify the package for cr7ia to apply it to crx10ia.

Please see #316 and #320. If you could finish that, you'd not have to start from scratch.

> We don't have R648(User Socket Messaging) function yet, so I don't know if it will work.

Without `R648`, the driver can't/won't work.
