### ISSUE TITLE
Any plan to update the fanuc ROS driver support to ROS 2 (foxy or humble)?

### ISSUE THREAD

**Issue by hyang5** [ros-industrial/fanuc#332]
As titled... is there any plan to update fanuc ROS drivers to support ROS 2 + MoveIt2?

**Comment by gavanderhoorn** [comment]
No, I have no immediate plans.

Main reason: this would also require packages like `industrial_robot_client` and `simple_message` to be ported, which is quite some work.

Additionally, the ROS API is so simple, and traffic so low-volume and low-rate, that the `ros1_bridge` (together with https://github.com/ros2/ros1_bridge/pull/256) should work sufficiently well.

If this was using `ros_control` with some sort of high-bandwidth interface to the Fanuc controller, then yes, it would not be usable without a proper port. But that's not the case.
