### ISSUE TITLE
Fanuc status on main page should be changed dynamically using wiki macros

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/fanuc#40]
The fanuc wiki main page ( http://wiki.ros.org/fanuc ), shows the software status for the groovy version.  "Groovy" is "hard coded" into the wiki.  The desired method of doing this is to use the wiki version macros as shown here: http://wiki.ros.org/Industrial/Software_Status#Full_Example.

In the future, we hope that the software status will be embedded in the auto-generated content at the top of each page.  This content is tied to ROS versions.  By following the example above the page layout will not change if/when this information becomes embedded in the auto-generated content.

**Comment by gavanderhoorn** [comment]
Done. See http://wiki.ros.org/fanuc?action=diff&rev1=8&rev2=9.
