### ISSUE TITLE
support: determine actual acceleration limits

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#49]
Acceleration limits currently specified in the Arm Navigation and MoveIt configuration packages are calculated values, not actual limits.

Todo: determine actual acceleration limits and update MoveIt configuration packages.
- [ ] M-10iA
- [ ] M-16iB/20
- [ ] M-20iA
- [ ] M-20iA/10L
- [ ] M-430iA/2F
- [ ] M-430iA/2P
- [ ] LR Mate 200iC
- [ ] LR Mate 200iC/5H
- [ ] LR Mate 200iD

**Comment by gavanderhoorn** [comment]
Closed by mistake. Reopening, as this is still an issue.

**Comment by gavanderhoorn** [comment]
This might now actually be possible - I've seen some interesting system variables on new controllers. But I don't know whether those values are correct/usable on older systems.

**Comment by jettan** [comment]
@gavanderhoorn Are the system variables you meant by any chance $CP_PARAMGRP[1].$jnt_acc_lim[*]? According to documentation this should be what we are looking for.

EDIT: Or maybe they are only for the Constant Path Motion function.

**Comment by gavanderhoorn** [comment]
The one you refer to is for constant path. But on recent controllers Fanuc seems to have added accell limit data where there used to be nothing.

**Comment by gavanderhoorn** [comment]
It's been some time, but with the appearance of Stream Motion we may actually be able to update the xacros with this information.

Wouldn't necessarily be the *actual* limits, but they will probably be close enough.

**Comment by gavanderhoorn** [comment]
Stream Motion limits are *not* the real limits of the hw.

It's doubtful any option on the controller gets to use the real limits, besides the main motion controller which TP uses.

As such, I'm going to close this.

**Comment by gavanderhoorn** [comment]
Furthermore: there is no single set of limits, they are payload, current pose and current velocity dependent.
