### ISSUE TITLE
Support package package.xml missing depends

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/fanuc#64]
The following depends are needed in support package package.xml files (they were found to be missing by using the roslaunch check macro):

```
 <run_depend>robot_state_publisher</run_depend>
 <run_depend>rviz</run_depend>
 <run_depend>joint_state_publisher</run_depend>
```

If the roslaunch check tests are included, the the following is also needed:

```
<build_depend>roslaunch</build_depend>
```

**Comment by gavanderhoorn** [comment]
Thanks for reporting.
