### ISSUE TITLE
Look into using convex_decomposition pkg for generating collision meshes

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#65]
Instead of creating those manually using Meshlab for instance.

See [convex_decomposition](http://wiki.ros.org/convex_decomposition) on the ROS wiki and the [github repository](https://github.com/ros/convex_decomposition).

**Comment by gavanderhoorn** [comment]
See the `CMakeLists.txt` in [katana_description](https://github.com/uos/katana_driver/blob/groovy/katana_description/CMakeLists.txt) for an example on how to use this during pkg building.

**Comment by shaun-edwards** [comment]
The wiki for `convex_decomposition` says it will be deprecated soon?

I would prefer that convex hull be built "manually" and verified rather than automatically as part of the build.  My reasoning is that the convex hulls are critical to safety and function.  If the build fails or the command line program that generates the hull fails, it's not clear that anyone would notice.

-1 from me.

**Comment by gavanderhoorn** [comment]
If the program encounters an error, the build fails, so that would certainly be noticable. Also, if the files are not generated, loading of all urdfs referencing them will fail, with lots of errors.

As to the deprecation: pr2_description still uses it, as do some other packages.

I want to take a look at the quality of the meshes the package generates. If they are good enough it could still be a nice thing to have. It takes quite some time to create N convex hulls for each manipulator in each support package.

**Comment by shaun-edwards** [comment]
There are problems that occur during manual generation that aren't failures, but could be problematic.  Re-orienting normals is very common.  I think we could utilize the tool to generate convex hulls, but we should verify them and then check them in.  I don't like the idea of everybody having to build them.

**Comment by gavanderhoorn** [comment]
Another candidate: [V-HACD](https://code.google.com/p/v-hacd/).

As it is rather slow, this is really not one to integrate into the build. It does produce nice convex hulls though.

**Comment by shaun-edwards** [comment]
How slow is slow?  I like the results.  Has it been ported to Github?  Should we port it so it isn't lost?

**Comment by gavanderhoorn** [comment]
> How slow is slow?

For the mesh shown in [this](https://github.com/ros-industrial/fanuc_experimental/pull/14#issuecomment-151975317) comment over at ros-industrial/fanuc_experimental#14, it took about 45 seconds on my machine (2.8 GHz dual core). But more complex meshes can take substantially longer (I've had one take something like 2 minutes already).

> I like the results.  Has it been ported to Github?  Should we port it so it isn't lost?

Yes, there are at least two imports already. I got a local clone as well that I could push to somewhere, if/when needed.

**Comment by gavanderhoorn** [comment]
And another candidate: [gaschler/bounding-mesh](https://github.com/gaschler/bounding-mesh).

**Comment by gavanderhoorn** [comment]
The tools / packages listed in this thread are interesting, but we won't be generating anything automatically at build time, so closing for now.
