### ISSUE TITLE
Allow runtime adjustment of MOVE_SPEED and MOVE_CNT

### ISSUE THREAD

**Issue by JeremyZoss** [ros-industrial/fanuc#71]
The TPE program ros_movesm.tp uses register values for key motion parameters (speed, continuation-zone).  These register values are written by ros_relay.kl every time a new motion message is received, using the values set in MOVE_SPEED and MOVE_CNT constants.

This design ensures that it is difficult to accidentally overwrite these key parameters (a good feature), but requires users to recompile ros_relay.kl to modify the values.  Not all users will have access to RoboGuide (especially in deployed installations), so this modification may be difficult.

A better design might be to only override the register values if they are "dangerous" (e.g. out-of-range).  This would allow users to adjust the parameters without the use of a KAREL compiler.

The ROS wiki tutorial page should also be updated to document the use of these parameters.  In the current implementation, ROS MoveIt commands will often timeout due to the large disparity between MoveIt's assumed motion speed (100%) and the default MOVE_SPEED value (20%).  Tweaking either MoveIt or MOVE_SPEED to harmonize these expectations is one of the first steps when deploying a Fanuc application on a "real robot".

**Comment by gavanderhoorn** [comment]
All true, however configuring `MOVE_SPEED` only makes sense as long as `ros_relay` doesn't use commanded velocities (#1). Making `MOVE_CNT` user configurable is certainly feasible.

Thanks for reporting.
