### ISSUE TITLE
driver: karel motion not supported on R-30iB

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#86]
Seems the Karel `MOVE ..` instructions have been removed from the R-30iB controllers, making TP motion the only available option.

Documenting this for future reference.

**Comment by gavanderhoorn** [comment]
Also, it appears Karel is not a standard option any more on the R30iB (ie: you have to explicitly order it).

**Comment by JeremyZoss** [comment]
FYI:  When we have purchased robots, Karel has never been a standard option.  We always need to explicitly request/add the Karel option when needed.

It's probably a good plan to avoid Karel-based motion commands anyway, as there are many warnings against driving multi-group motion commands from Karel.  It makes sense to leave open the option to support multi-group motion, for multi-arm workcells.

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:

> FYI: When we have purchased robots, Karel has never been a standard option. We always need to explicitly request/add the Karel option when needed.

Ok, interesting. I've understood that the option was always there in R-30iA and earlier (and in my limited amount of experience that has been true so far).

> It's probably a good plan to avoid Karel-based motion commands anyway, as there are many warnings against driving multi-group motion commands from Karel.

Sure, that is why the Karel motion option was removed in an earlier version of the driver.

In any case I was just documenting the change, but thanks for the additional information.

**Comment by gavanderhoorn** [comment]
Using `MOVE ..` has been deprecated for some time now, so is not a viable approach to motion control for a driver in any case, regardless of whether it is supported in R-30iB controllers.

Unfortunately, TP is the way forward.

So closing.
