### ISSUE TITLE
driver: Karel CANCEL statement upon TRAJ_STOP has no effect

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#93]
Upon receiving a _Trajectory Stop_ special sequence number, the current implementation calls the `CANCEL` Karel built-in. According to the manual (Karel refman), this statement only affects the groups over which the callee has motion control. As the relay has no motion groups locked (`ros_movesm` performs the motions), the statement has no effect. The manipulator does stop, but only because the ROS node stops sending new trajectory points.

_Trajectory Stop_ should be handled properly.

**Comment by tuanhai59** [comment]
When trajectory stop is issued, I set a flag in karel and in ros_movesm I skip the motion based on the value of the flag. The manipulator does stop but the problem is that if the motion is in progress and it takes too long then during that time the trajectory stop can not be received by ros_relay. It must finish the movement first and then receive the new message (with stop command). Can we handle the trajectory stop separately which can reacts immediately?

**Comment by gavanderhoorn** [comment]
If I understand you correctly, you've added a `SKIP` to the `J` motion statement in `ros_movesm` [here](https://github.com/ros-industrial/fanuc/blob/246749a73d4719cc23ef33454930167750bfe00e/fanuc_driver/tpe/ros_movesm.ls#L43), and whenever `ros_relay` receives a `RI_SEQ_STPRJ` (`-4`) [here](https://github.com/ros-industrial/fanuc/blob/d00beba883fa5806f9a8cb93d5c2683184d3ce00/fanuc_driver/karel/ros_relay.kl#L304), it triggers the skip and `ros_movesm` should stop the current motion. Correct?

> [..] if the motion is in progress and it takes too long then during that time the trajectory stop can not be received by ros_relay. It must finish the movement first and then receive the new message (with stop command).

The handshake between `ros_movesm` and `ros_relay` is structured such that `ros_movesm` first copies the target trajectory point, then acknowledges the reception of the new point and only after that starts the motion. `ros_relay` at that point is free to do what it wants / needs.

Are you saying that you see that `ros_movesm` seems to wait for the completion of the motion before it acknowledges the copy and thus `ros_relay` is blocked and cannot deal with network traffic?

**Comment by tuanhai59** [comment]
Yes, I use skip inside the J move command and the skip condition is trigged via ros_relay when seq = -4. 
I mean the handshaking between ros_movesm and ros_relay blocks the future message. the future message here is not the next message but the after one of the next message. I have tested it in roboguide and did the real experiment.  for example I put a delay 10[s] command in ros_movesm. During the delay time or motion, If you push the stop service, it doesn't response immediately (it can be seen on Teachpendant panel)

**Comment by gavanderhoorn** [comment]
> I mean the handshaking between `ros_movesm` and `ros_relay` blocks the future message.

Well, that is what I was asking: the way it is structured now is that the move is initiated _after_ the data copy phase has been acknowledged. In theory, `ros_movesm` should ACK `ros_relay` (by making the 'data ready' flag low again) _before_ it starts the motion. So during the motion, `ros_relay` is no longer waiting [here](https://github.com/ros-industrial/fanuc/blob/d00beba883fa5806f9a8cb93d5c2683184d3ce00/fanuc_driver/karel/ros_relay.kl#L505).

At least that is how it was implemented, and what I have verified here locally.

Just to be sure: you are saying that `ros_movesm`does _not_ ACK the copy until it has finished the motion, and that `ros_relay` is essentially hanging [here](https://github.com/ros-industrial/fanuc/blob/d00beba883fa5806f9a8cb93d5c2683184d3ce00/fanuc_driver/karel/ros_relay.kl#L505):

``` pascal
WAIT FOR (FLG[cfg.f_msm_drdy] = OFF)
```

not handling network traffic?

If so, you could try adding a `BREAK` to the `J` statement in `ros_movesm`, but I doubt that will really matter. It will probably make motion performance even worse.

If that doesn't help, I'll have to investigate.

**Comment by tuanhai59** [comment]
No, the ros_relay waits at this command: `WAIT FOR (FLG[cfg.f_msm_rdy] = ON)`.

Because before ros_movesm starts the motion, it set this `FLG(cfg.f_msm_rdy) =  off`. In the next loop of the `ros_relay` will `WAIT FOR (FLG[cfg.f_msm_rdy] = ON)`.

**Comment by gavanderhoorn** [comment]
Ah, right.

It's not pretty, but what you could potentially do is something like (in `ros_relay`):

``` pascal
ROUTINE exec_move_
  ...
BEGIN
  ...
  WAIT FOR ((FLG[cfg.f_msm_rdy] = ON) OR (FLG[skip_flag] = ON))

  -- see if skip_flag was set while we were waiting
  IF (FLG[skip_flag] = ON) THEN
    RETURN (define_some_appropriate_exit_code)
  ENDIF

  -- skip_flag not set, ros_movesm is ready for new data
  ...
```

As `ros_movesm` handles the `SKIP` condition in parallel, that is probably the quickest way to react to a `TRAJ_STOP`.

You'll also need to make sure that `skip_flag` is reset at the appropriate time (so that both `ros_movesm` and `ros_relay` have had a chance to act upon it).

**Comment by tuanhai59** [comment]
Well, the `FLG[skip_flag]` is set by the `pkt_in_.seq_nr_`. if the `FLG[skip_flag] = OFF`, it will never be updated because you didn't polling the new message (where stop command can be issued) and you got stuck at this command. So I will try but I doub that it will work.

Instead of `WAIT FOR ((FLG[cfg.f_msm_rdy] = ON)`, I used below block of command to replace but I doesn't work.

``` pascal
    WHILE  (FLG[cfg.f_msm_rdy] = OFF) DO -- when rosmovesm still busy with the movement
        WRITE('rosmove sm is busy',CR)
        stat__ = ipkt_checkfd(fd, pkt)
        IF (pkt.seq_nr_=-4) THEN
            WRITE('stop issued',CR)
            --Set Flag for the skip condition
        ENDIF   
        DELAY 100
    endwhile
```

**Comment by gavanderhoorn** [comment]
Yes, I hadn't taken the prefetching behaviour into account.

I'm afraid without decoupling the network traffic handling from the motion queueing more than it is now (ie: by introducing a buffer), it's not going to be possible to do this elegantly. Your proposed approach would probably also not interact very nicely with the rest of the control flow, as that assumes it has complete control over the socket handling.

**Comment by tuanhai59** [comment]
Yes, I also think about a queue/buffer for the message but it is difficult to define the size of the buffer. Because if I remove the handshaking, we have to control the number of message in such way it does not overflow.

I am thinking of using socket number 5 to communicate with the controller. Just simple program to set a flag, Digital I/O. Do you think it is possible?

**Comment by gavanderhoorn** [comment]
> I am thinking of using socket number 5 to communicate with the controller. Just simple program to set a flag, Digital I/O. Do you think it is possible?

That would certainly be possible, but will be more work on the ROS/MoveIt side: somehow you'll have to handle the goal cancellation then to be send through your separate socket connection. Possible, but involved.

**Comment by tuanhai59** [comment]
That is true. For me it is possible in the fanuc side and more complicated to integrate in the ros/moveit side. Do we have a node which send a simple message to Fanuc?

**Comment by gavanderhoorn** [comment]
> Do we have a node which send a simple message to Fanuc?

If by 'a simple message' you actually mean a `simple_message` message, then you could take a look at `simple_message` and `industrial_robot_client` in [industrial_core](https://github.com/ros-industrial/industrial_core).

Or if your timing requirements are not _that_ strict, you could see whether [fanuc_ros_cgio_py](https://github.com/gavanderhoorn/fanuc_ros_cgio_py) would work for you.

**Comment by tuanhai59** [comment]
Thanks! I will take a look.

**Comment by gavanderhoorn** [comment]
The new driver improves on the behaviour of the current one, but because of ros-industrial/industrial_core#175, there will be some changes needed to `industrial_robot_client` for this to work correctly.

**Comment by gavanderhoorn** [comment]
This will not be addressed any more in `fanuc_driver` - other developments will take priority.

Community contributions will be accepted though.

Note that `fanuc_driver_exp` improves on the current state in `fanuc_driver`, but still needs ros-industrial/industrial_core#175.

Closing.
