### ISSUE TITLE
ikfast: document success rate of IKFast generated plugins 

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#99]
As part of the plugin generation process, openrave runs a number of IK tests, which ultimately results in output like:

```
openravepy.databases.inversekinematics: testik, \
  success rate: 0.930000, \
  wrong solutions: 0.000000, \
  no solutions: 0.070000, \
  missing solution: 0.470000
```

Additional output is a list of exactly which tests failed (trial nr, joint angles, etc).

This is important data, as it provides an indication of the 'quality' of a provided IK plugin, and should probably be included with a `*_moveit_plugins` pkg documentation.

**Comment by gavanderhoorn** [comment]
Also related to #112.

**Comment by simonschmeisser** [comment]
Can you give some info on how to use this test? I just created a new ikfast plugin for an lrmate200ic and it completely doesn't work (ikfast gives 0 solutions, even before checking validity). The one provided was somewhat running, but did not give very useful results. kdl works just fine

**Comment by gavanderhoorn** [comment]
I'll see if I can find my notes, but I'm more interested in / worried about:

> The one provided was somewhat running, but did not give very useful results

You mean that `fanuc_lrmate200ic_moveit_plugins` didn't work for you?

If so, could you please report that in a new issue?

**Comment by gavanderhoorn** [comment]
As we're migrating to OPW kinematics (#245), this issue is no longer relevant.

Closing.
